/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as TrackersRouteImport } from './routes/trackers'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RepairRouteImport } from './routes/repair'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ImportExportRouteImport } from './routes/import-export'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DatabasesRouteImport } from './routes/databases'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as PageIdRouteImport } from './routes/page.$id'
import { Route as NotesIdRouteImport } from './routes/notes.$id'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersRoute = TrackersRouteImport.update({
  id: '/trackers',
  path: '/trackers',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRoute = RepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportExportRoute = ImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesRoute = DatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageIdRoute = PageIdRouteImport.update({
  id: '/page/$id',
  path: '/page/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blueprint': typeof BlueprintRoute
  '/calendar': typeof CalendarRoute
  '/databases': typeof DatabasesRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/goals': typeof GoalsRoute
  '/graph': typeof GraphRoute
  '/import-export': typeof ImportExportRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRoute
  '/repair': typeof RepairRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/trackers': typeof TrackersRoute
  '/trash': typeof TrashRoute
  '/vault': typeof VaultRoute
  '/notes/$id': typeof NotesIdRoute
  '/page/$id': typeof PageIdRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blueprint': typeof BlueprintRoute
  '/calendar': typeof CalendarRoute
  '/databases': typeof DatabasesRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/goals': typeof GoalsRoute
  '/graph': typeof GraphRoute
  '/import-export': typeof ImportExportRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRoute
  '/repair': typeof RepairRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/trackers': typeof TrackersRoute
  '/trash': typeof TrashRoute
  '/vault': typeof VaultRoute
  '/notes/$id': typeof NotesIdRoute
  '/page/$id': typeof PageIdRoute
  '/notes': typeof NotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blueprint': typeof BlueprintRoute
  '/calendar': typeof CalendarRoute
  '/databases': typeof DatabasesRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/goals': typeof GoalsRoute
  '/graph': typeof GraphRoute
  '/import-export': typeof ImportExportRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRoute
  '/repair': typeof RepairRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/trackers': typeof TrackersRoute
  '/trash': typeof TrashRoute
  '/vault': typeof VaultRoute
  '/notes/$id': typeof NotesIdRoute
  '/page/$id': typeof PageIdRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blueprint'
    | '/calendar'
    | '/databases'
    | '/documents'
    | '/finance'
    | '/goals'
    | '/graph'
    | '/import-export'
    | '/people'
    | '/projects'
    | '/repair'
    | '/search'
    | '/settings'
    | '/templates'
    | '/trackers'
    | '/trash'
    | '/vault'
    | '/notes/$id'
    | '/page/$id'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blueprint'
    | '/calendar'
    | '/databases'
    | '/documents'
    | '/finance'
    | '/goals'
    | '/graph'
    | '/import-export'
    | '/people'
    | '/projects'
    | '/repair'
    | '/search'
    | '/settings'
    | '/templates'
    | '/trackers'
    | '/trash'
    | '/vault'
    | '/notes/$id'
    | '/page/$id'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/blueprint'
    | '/calendar'
    | '/databases'
    | '/documents'
    | '/finance'
    | '/goals'
    | '/graph'
    | '/import-export'
    | '/people'
    | '/projects'
    | '/repair'
    | '/search'
    | '/settings'
    | '/templates'
    | '/trackers'
    | '/trash'
    | '/vault'
    | '/notes/$id'
    | '/page/$id'
    | '/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlueprintRoute: typeof BlueprintRoute
  CalendarRoute: typeof CalendarRoute
  DatabasesRoute: typeof DatabasesRoute
  DocumentsRoute: typeof DocumentsRoute
  FinanceRoute: typeof FinanceRoute
  GoalsRoute: typeof GoalsRoute
  GraphRoute: typeof GraphRoute
  ImportExportRoute: typeof ImportExportRoute
  PeopleRoute: typeof PeopleRoute
  ProjectsRoute: typeof ProjectsRoute
  RepairRoute: typeof RepairRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  TrackersRoute: typeof TrackersRoute
  TrashRoute: typeof TrashRoute
  VaultRoute: typeof VaultRoute
  NotesIdRoute: typeof NotesIdRoute
  PageIdRoute: typeof PageIdRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers': {
      id: '/trackers'
      path: '/trackers'
      fullPath: '/trackers'
      preLoaderRoute: typeof TrackersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-export': {
      id: '/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof ImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases': {
      id: '/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$id': {
      id: '/page/$id'
      path: '/page/$id'
      fullPath: '/page/$id'
      preLoaderRoute: typeof PageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlueprintRoute: BlueprintRoute,
  CalendarRoute: CalendarRoute,
  DatabasesRoute: DatabasesRoute,
  DocumentsRoute: DocumentsRoute,
  FinanceRoute: FinanceRoute,
  GoalsRoute: GoalsRoute,
  GraphRoute: GraphRoute,
  ImportExportRoute: ImportExportRoute,
  PeopleRoute: PeopleRoute,
  ProjectsRoute: ProjectsRoute,
  RepairRoute: RepairRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  TrackersRoute: TrackersRoute,
  TrashRoute: TrashRoute,
  VaultRoute: VaultRoute,
  NotesIdRoute: NotesIdRoute,
  PageIdRoute: PageIdRoute,
  NotesIndexRoute: NotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
